parameters:
    pim_extended_attribute_type.attribute_type.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\AttributeType\TextCollectionType
    pim_extended_attribute_type.validator.constraint_guesser.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Validator\ConstraintGuesser\TextCollectionGuesser

services:
    pim_extended_attribute_type.attribute_type.text_collection:
        class: '%pim_extended_attribute_type.attribute_type.text_collection.class%'
        arguments:
            - 'text_collection'
        tags:
            - { name: pim_catalog.attribute_type, alias: pim_catalog_text_collection }
