parameters:
    pim_extended_attribute_type.completeness.checker.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Completeness\Checker\TextCollectionCompleteChecker

services:
    pim_extended_attribute_type.completeness.checker.text_collection:
        class: '%pim_extended_attribute_type.completeness.checker.text_collection.class%'
        arguments:
            - '@pim_catalog.repository.cached_attribute'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }
